/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sx.spyglass.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AppPort service. Represents a row in the &quot;FOO_AppPort&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.sx.spyglass.model.impl.AppPortModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.sx.spyglass.model.impl.AppPortImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppPort
 * @generated
 */
@ProviderType
public interface AppPortModel extends BaseModel<AppPort> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a app port model instance should use the {@link AppPort} interface instead.
	 */

	/**
	 * Returns the primary key of this app port.
	 *
	 * @return the primary key of this app port
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this app port.
	 *
	 * @param primaryKey the primary key of this app port
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the app port ID of this app port.
	 *
	 * @return the app port ID of this app port
	 */
	public long getAppPortId();

	/**
	 * Sets the app port ID of this app port.
	 *
	 * @param appPortId the app port ID of this app port
	 */
	public void setAppPortId(long appPortId);

	/**
	 * Returns the science app ID of this app port.
	 *
	 * @return the science app ID of this app port
	 */
	public long getScienceAppId();

	/**
	 * Sets the science app ID of this app port.
	 *
	 * @param scienceAppId the science app ID of this app port
	 */
	public void setScienceAppId(long scienceAppId);

	/**
	 * Returns the data type ID of this app port.
	 *
	 * @return the data type ID of this app port
	 */
	public long getDataTypeId();

	/**
	 * Sets the data type ID of this app port.
	 *
	 * @param dataTypeId the data type ID of this app port
	 */
	public void setDataTypeId(long dataTypeId);

	/**
	 * Returns the option name of this app port.
	 *
	 * @return the option name of this app port
	 */
	@AutoEscape
	public String getOptionName();

	/**
	 * Sets the option name of this app port.
	 *
	 * @param optionName the option name of this app port
	 */
	public void setOptionName(String optionName);

	/**
	 * Returns the port type of this app port.
	 *
	 * @return the port type of this app port
	 */
	@AutoEscape
	public String getPortType();

	/**
	 * Sets the port type of this app port.
	 *
	 * @param portType the port type of this app port
	 */
	public void setPortType(String portType);

}