/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.sx.spyglass.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedGroupedModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ScienceApp service. Represents a row in the &quot;SXSpyglass_ScienceApp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.sx.spyglass.model.impl.ScienceAppModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.sx.spyglass.model.impl.ScienceAppImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ScienceApp
 * @generated
 */
@ProviderType
public interface ScienceAppModel
	extends BaseModel<ScienceApp>, LocalizedModel, ShardedModel,
			StagedGroupedModel, TrashedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a science app model instance should use the {@link ScienceApp} interface instead.
	 */

	/**
	 * Returns the primary key of this science app.
	 *
	 * @return the primary key of this science app
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this science app.
	 *
	 * @param primaryKey the primary key of this science app
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this science app.
	 *
	 * @return the uuid of this science app
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this science app.
	 *
	 * @param uuid the uuid of this science app
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the science app ID of this science app.
	 *
	 * @return the science app ID of this science app
	 */
	public long getScienceAppId();

	/**
	 * Sets the science app ID of this science app.
	 *
	 * @param scienceAppId the science app ID of this science app
	 */
	public void setScienceAppId(long scienceAppId);

	/**
	 * Returns the group ID of this science app.
	 *
	 * @return the group ID of this science app
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this science app.
	 *
	 * @param groupId the group ID of this science app
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this science app.
	 *
	 * @return the company ID of this science app
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this science app.
	 *
	 * @param companyId the company ID of this science app
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this science app.
	 *
	 * @return the user ID of this science app
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this science app.
	 *
	 * @param userId the user ID of this science app
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this science app.
	 *
	 * @return the user uuid of this science app
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this science app.
	 *
	 * @param userUuid the user uuid of this science app
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this science app.
	 *
	 * @return the user name of this science app
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this science app.
	 *
	 * @param userName the user name of this science app
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this science app.
	 *
	 * @return the create date of this science app
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this science app.
	 *
	 * @param createDate the create date of this science app
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this science app.
	 *
	 * @return the modified date of this science app
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this science app.
	 *
	 * @param modifiedDate the modified date of this science app
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this science app.
	 *
	 * @return the status of this science app
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this science app.
	 *
	 * @param status the status of this science app
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this science app.
	 *
	 * @return the status by user ID of this science app
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this science app.
	 *
	 * @param statusByUserId the status by user ID of this science app
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this science app.
	 *
	 * @return the status by user uuid of this science app
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this science app.
	 *
	 * @param statusByUserUuid the status by user uuid of this science app
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this science app.
	 *
	 * @return the status by user name of this science app
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this science app.
	 *
	 * @param statusByUserName the status by user name of this science app
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this science app.
	 *
	 * @return the status date of this science app
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this science app.
	 *
	 * @param statusDate the status date of this science app
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the last publish date of this science app.
	 *
	 * @return the last publish date of this science app
	 */
	@Override
	public Date getLastPublishDate();

	/**
	 * Sets the last publish date of this science app.
	 *
	 * @param lastPublishDate the last publish date of this science app
	 */
	@Override
	public void setLastPublishDate(Date lastPublishDate);

	/**
	 * Returns the app name of this science app.
	 *
	 * @return the app name of this science app
	 */
	@AutoEscape
	public String getAppName();

	/**
	 * Sets the app name of this science app.
	 *
	 * @param appName the app name of this science app
	 */
	public void setAppName(String appName);

	/**
	 * Returns the app version of this science app.
	 *
	 * @return the app version of this science app
	 */
	@AutoEscape
	public String getAppVersion();

	/**
	 * Sets the app version of this science app.
	 *
	 * @param appVersion the app version of this science app
	 */
	public void setAppVersion(String appVersion);

	/**
	 * Returns the app type of this science app.
	 *
	 * @return the app type of this science app
	 */
	@AutoEscape
	public String getAppType();

	/**
	 * Sets the app type of this science app.
	 *
	 * @param appType the app type of this science app
	 */
	public void setAppType(String appType);

	/**
	 * Returns the exe file name of this science app.
	 *
	 * @return the exe file name of this science app
	 */
	@AutoEscape
	public String getExeFileName();

	/**
	 * Sets the exe file name of this science app.
	 *
	 * @param exeFileName the exe file name of this science app
	 */
	public void setExeFileName(String exeFileName);

	/**
	 * Returns the display name of this science app.
	 *
	 * @return the display name of this science app
	 */
	public String getDisplayName();

	/**
	 * Returns the localized display name of this science app in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized display name of this science app
	 */
	@AutoEscape
	public String getDisplayName(Locale locale);

	/**
	 * Returns the localized display name of this science app in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized display name of this science app. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDisplayName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized display name of this science app in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized display name of this science app
	 */
	@AutoEscape
	public String getDisplayName(String languageId);

	/**
	 * Returns the localized display name of this science app in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized display name of this science app
	 */
	@AutoEscape
	public String getDisplayName(String languageId, boolean useDefault);

	@AutoEscape
	public String getDisplayNameCurrentLanguageId();

	@AutoEscape
	public String getDisplayNameCurrentValue();

	/**
	 * Returns a map of the locales and localized display names of this science app.
	 *
	 * @return the locales and localized display names of this science app
	 */
	public Map<Locale, String> getDisplayNameMap();

	/**
	 * Sets the display name of this science app.
	 *
	 * @param displayName the display name of this science app
	 */
	public void setDisplayName(String displayName);

	/**
	 * Sets the localized display name of this science app in the language.
	 *
	 * @param displayName the localized display name of this science app
	 * @param locale the locale of the language
	 */
	public void setDisplayName(String displayName, Locale locale);

	/**
	 * Sets the localized display name of this science app in the language, and sets the default locale.
	 *
	 * @param displayName the localized display name of this science app
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDisplayName(
		String displayName, Locale locale, Locale defaultLocale);

	public void setDisplayNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized display names of this science app from the map of locales and localized display names.
	 *
	 * @param displayNameMap the locales and localized display names of this science app
	 */
	public void setDisplayNameMap(Map<Locale, String> displayNameMap);

	/**
	 * Sets the localized display names of this science app from the map of locales and localized display names, and sets the default locale.
	 *
	 * @param displayNameMap the locales and localized display names of this science app
	 * @param defaultLocale the default locale
	 */
	public void setDisplayNameMap(
		Map<Locale, String> displayNameMap, Locale defaultLocale);

	/**
	 * Returns the description of this science app.
	 *
	 * @return the description of this science app
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this science app in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this science app
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this science app in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this science app. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this science app in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this science app
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this science app in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this science app
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this science app.
	 *
	 * @return the locales and localized descriptions of this science app
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this science app.
	 *
	 * @param description the description of this science app
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this science app in the language.
	 *
	 * @param description the localized description of this science app
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this science app in the language, and sets the default locale.
	 *
	 * @param description the localized description of this science app
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(
		String description, Locale locale, Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this science app from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this science app
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this science app from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this science app
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale);

	/**
	 * Returns the start script of this science app.
	 *
	 * @return the start script of this science app
	 */
	@AutoEscape
	public String getStartScript();

	/**
	 * Sets the start script of this science app.
	 *
	 * @param startScript the start script of this science app
	 */
	public void setStartScript(String startScript);

	/**
	 * Returns the finish script of this science app.
	 *
	 * @return the finish script of this science app
	 */
	@AutoEscape
	public String getFinishScript();

	/**
	 * Sets the finish script of this science app.
	 *
	 * @param finishScript the finish script of this science app
	 */
	public void setFinishScript(String finishScript);

	/**
	 * Returns the trash entry created when this science app was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this science app.
	 *
	 * @return the trash entry created when this science app was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this science app.
	 *
	 * @return the class primary key of the trash entry for this science app
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this science app.
	 *
	 * @return the trash handler for this science app
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this science app is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this science app is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this science app is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this science app is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

	/**
	 * Returns <code>true</code> if this science app is approved.
	 *
	 * @return <code>true</code> if this science app is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this science app is denied.
	 *
	 * @return <code>true</code> if this science app is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this science app is a draft.
	 *
	 * @return <code>true</code> if this science app is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this science app is expired.
	 *
	 * @return <code>true</code> if this science app is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this science app is inactive.
	 *
	 * @return <code>true</code> if this science app is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this science app is incomplete.
	 *
	 * @return <code>true</code> if this science app is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this science app is pending.
	 *
	 * @return <code>true</code> if this science app is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this science app is scheduled.
	 *
	 * @return <code>true</code> if this science app is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

}