/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.sx.spyglass.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.sx.spyglass.model.AppPort;
import com.sx.spyglass.model.AppPortModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AppPort service. Represents a row in the &quot;SXSpyglass_AppPort&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AppPortModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppPortImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppPortImpl
 * @generated
 */
public class AppPortModelImpl
	extends BaseModelImpl<AppPort> implements AppPortModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a app port model instance should use the <code>AppPort</code> interface instead.
	 */
	public static final String TABLE_NAME = "SXSpyglass_AppPort";

	public static final Object[][] TABLE_COLUMNS = {
		{"appPortId", Types.BIGINT}, {"scienceAppId", Types.BIGINT},
		{"dataTypeId", Types.BIGINT}, {"optionName", Types.VARCHAR},
		{"portType", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("appPortId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("scienceAppId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("optionName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("portType", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SXSpyglass_AppPort (appPortId LONG not null primary key,scienceAppId LONG,dataTypeId LONG,optionName VARCHAR(75) null,portType VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table SXSpyglass_AppPort";

	public static final String ORDER_BY_JPQL =
		" ORDER BY appPort.appPortId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SXSpyglass_AppPort.appPortId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long DATATYPEID_COLUMN_BITMASK = 1L;

	public static final long PORTTYPE_COLUMN_BITMASK = 2L;

	public static final long APPPORTID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public AppPortModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _appPortId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAppPortId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appPortId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AppPort.class;
	}

	@Override
	public String getModelClassName() {
		return AppPort.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AppPort, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AppPort, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppPort, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((AppPort)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AppPort, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AppPort, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AppPort)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AppPort, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AppPort, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<AppPort, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<AppPort, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<AppPort, Object>>();

		attributeGetterFunctions.put("appPortId", AppPort::getAppPortId);
		attributeGetterFunctions.put("scienceAppId", AppPort::getScienceAppId);
		attributeGetterFunctions.put("dataTypeId", AppPort::getDataTypeId);
		attributeGetterFunctions.put("optionName", AppPort::getOptionName);
		attributeGetterFunctions.put("portType", AppPort::getPortType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<AppPort, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<AppPort, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<AppPort, ?>>();

		attributeSetterBiConsumers.put(
			"appPortId", (BiConsumer<AppPort, Long>)AppPort::setAppPortId);
		attributeSetterBiConsumers.put(
			"scienceAppId",
			(BiConsumer<AppPort, Long>)AppPort::setScienceAppId);
		attributeSetterBiConsumers.put(
			"dataTypeId", (BiConsumer<AppPort, Long>)AppPort::setDataTypeId);
		attributeSetterBiConsumers.put(
			"optionName", (BiConsumer<AppPort, String>)AppPort::setOptionName);
		attributeSetterBiConsumers.put(
			"portType", (BiConsumer<AppPort, String>)AppPort::setPortType);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getAppPortId() {
		return _appPortId;
	}

	@Override
	public void setAppPortId(long appPortId) {
		_appPortId = appPortId;
	}

	@Override
	public long getScienceAppId() {
		return _scienceAppId;
	}

	@Override
	public void setScienceAppId(long scienceAppId) {
		_scienceAppId = scienceAppId;
	}

	@Override
	public long getDataTypeId() {
		return _dataTypeId;
	}

	@Override
	public void setDataTypeId(long dataTypeId) {
		_columnBitmask |= DATATYPEID_COLUMN_BITMASK;

		if (!_setOriginalDataTypeId) {
			_setOriginalDataTypeId = true;

			_originalDataTypeId = _dataTypeId;
		}

		_dataTypeId = dataTypeId;
	}

	public long getOriginalDataTypeId() {
		return _originalDataTypeId;
	}

	@Override
	public String getOptionName() {
		if (_optionName == null) {
			return "";
		}
		else {
			return _optionName;
		}
	}

	@Override
	public void setOptionName(String optionName) {
		_optionName = optionName;
	}

	@Override
	public String getPortType() {
		if (_portType == null) {
			return "";
		}
		else {
			return _portType;
		}
	}

	@Override
	public void setPortType(String portType) {
		_columnBitmask |= PORTTYPE_COLUMN_BITMASK;

		if (_originalPortType == null) {
			_originalPortType = _portType;
		}

		_portType = portType;
	}

	public String getOriginalPortType() {
		return GetterUtil.getString(_originalPortType);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, AppPort.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AppPort toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AppPort>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AppPortImpl appPortImpl = new AppPortImpl();

		appPortImpl.setAppPortId(getAppPortId());
		appPortImpl.setScienceAppId(getScienceAppId());
		appPortImpl.setDataTypeId(getDataTypeId());
		appPortImpl.setOptionName(getOptionName());
		appPortImpl.setPortType(getPortType());

		appPortImpl.resetOriginalValues();

		return appPortImpl;
	}

	@Override
	public int compareTo(AppPort appPort) {
		long primaryKey = appPort.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AppPort)) {
			return false;
		}

		AppPort appPort = (AppPort)object;

		long primaryKey = appPort.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalDataTypeId = _dataTypeId;

		_setOriginalDataTypeId = false;

		_originalPortType = _portType;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AppPort> toCacheModel() {
		AppPortCacheModel appPortCacheModel = new AppPortCacheModel();

		appPortCacheModel.appPortId = getAppPortId();

		appPortCacheModel.scienceAppId = getScienceAppId();

		appPortCacheModel.dataTypeId = getDataTypeId();

		appPortCacheModel.optionName = getOptionName();

		String optionName = appPortCacheModel.optionName;

		if ((optionName != null) && (optionName.length() == 0)) {
			appPortCacheModel.optionName = null;
		}

		appPortCacheModel.portType = getPortType();

		String portType = appPortCacheModel.portType;

		if ((portType != null) && (portType.length() == 0)) {
			appPortCacheModel.portType = null;
		}

		return appPortCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AppPort, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AppPort, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppPort, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AppPort)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AppPort, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AppPort, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppPort, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((AppPort)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AppPort>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AppPort.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _appPortId;
	private long _scienceAppId;
	private long _dataTypeId;
	private long _originalDataTypeId;
	private boolean _setOriginalDataTypeId;
	private String _optionName;
	private String _portType;
	private String _originalPortType;
	private long _columnBitmask;
	private AppPort _escapedModel;

}