/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.sx.spyglass.model.impl;

import com.sx.spyglass.model.AppPort;
import com.sx.spyglass.service.AppPortLocalServiceUtil;

/**
 * The extended model base implementation for the AppPort service. Represents a row in the &quot;SXSpyglass_AppPort&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppPortImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppPortImpl
 * @see AppPort
 * @generated
 */
public abstract class AppPortBaseImpl
	extends AppPortModelImpl implements AppPort {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a app port model instance should use the <code>AppPort</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AppPortLocalServiceUtil.addAppPort(this);
		}
		else {
			AppPortLocalServiceUtil.updateAppPort(this);
		}
	}

}