/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sx.spyglass.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import com.sx.spyglass.model.ScienceApp;
import com.sx.spyglass.model.ScienceAppModel;
import com.sx.spyglass.model.ScienceAppSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ScienceApp service. Represents a row in the &quot;FOO_ScienceApp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ScienceAppModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ScienceAppImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ScienceAppImpl
 * @generated
 */
@JSON(strict = true)
public class ScienceAppModelImpl
	extends BaseModelImpl<ScienceApp> implements ScienceAppModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a science app model instance should use the <code>ScienceApp</code> interface instead.
	 */
	public static final String TABLE_NAME = "FOO_ScienceApp";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"scienceAppId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"lastPublishDate", Types.TIMESTAMP}, {"appName", Types.VARCHAR},
		{"appVersion", Types.VARCHAR}, {"appType", Types.VARCHAR},
		{"exeFileName", Types.VARCHAR}, {"displayName", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"startScript", Types.VARCHAR},
		{"finishScript", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("scienceAppId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("appName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("appVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("appType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("exeFileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("displayName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startScript", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("finishScript", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FOO_ScienceApp (uuid_ VARCHAR(75) null,scienceAppId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,lastPublishDate DATE null,appName VARCHAR(75) null,appVersion VARCHAR(75) null,appType VARCHAR(75) null,exeFileName VARCHAR(75) null,displayName STRING null,description STRING null,startScript VARCHAR(75) null,finishScript VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table FOO_ScienceApp";

	public static final String ORDER_BY_JPQL =
		" ORDER BY scienceApp.appName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FOO_ScienceApp.appName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long APPNAME_COLUMN_BITMASK = 1L;

	public static final long APPTYPE_COLUMN_BITMASK = 2L;

	public static final long APPVERSION_COLUMN_BITMASK = 4L;

	public static final long COMPANYID_COLUMN_BITMASK = 8L;

	public static final long GROUPID_COLUMN_BITMASK = 16L;

	public static final long STATUS_COLUMN_BITMASK = 32L;

	public static final long USERID_COLUMN_BITMASK = 64L;

	public static final long UUID_COLUMN_BITMASK = 128L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ScienceApp toModel(ScienceAppSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ScienceApp model = new ScienceAppImpl();

		model.setUuid(soapModel.getUuid());
		model.setScienceAppId(soapModel.getScienceAppId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setLastPublishDate(soapModel.getLastPublishDate());
		model.setAppName(soapModel.getAppName());
		model.setAppVersion(soapModel.getAppVersion());
		model.setAppType(soapModel.getAppType());
		model.setExeFileName(soapModel.getExeFileName());
		model.setDisplayName(soapModel.getDisplayName());
		model.setDescription(soapModel.getDescription());
		model.setStartScript(soapModel.getStartScript());
		model.setFinishScript(soapModel.getFinishScript());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ScienceApp> toModels(ScienceAppSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ScienceApp> models = new ArrayList<ScienceApp>(soapModels.length);

		for (ScienceAppSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ScienceAppModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _scienceAppId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setScienceAppId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _scienceAppId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ScienceApp.class;
	}

	@Override
	public String getModelClassName() {
		return ScienceApp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ScienceApp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ScienceApp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ScienceApp, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((ScienceApp)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ScienceApp, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ScienceApp, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ScienceApp)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ScienceApp, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ScienceApp, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ScienceApp, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ScienceApp, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ScienceApp, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ScienceApp, Object>>();
		Map<String, BiConsumer<ScienceApp, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ScienceApp, ?>>();

		attributeGetterFunctions.put("uuid", ScienceApp::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<ScienceApp, String>)ScienceApp::setUuid);
		attributeGetterFunctions.put(
			"scienceAppId", ScienceApp::getScienceAppId);
		attributeSetterBiConsumers.put(
			"scienceAppId",
			(BiConsumer<ScienceApp, Long>)ScienceApp::setScienceAppId);
		attributeGetterFunctions.put("groupId", ScienceApp::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<ScienceApp, Long>)ScienceApp::setGroupId);
		attributeGetterFunctions.put("companyId", ScienceApp::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ScienceApp, Long>)ScienceApp::setCompanyId);
		attributeGetterFunctions.put("userId", ScienceApp::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<ScienceApp, Long>)ScienceApp::setUserId);
		attributeGetterFunctions.put("userName", ScienceApp::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<ScienceApp, String>)ScienceApp::setUserName);
		attributeGetterFunctions.put("createDate", ScienceApp::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ScienceApp, Date>)ScienceApp::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ScienceApp::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ScienceApp, Date>)ScienceApp::setModifiedDate);
		attributeGetterFunctions.put("status", ScienceApp::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<ScienceApp, Integer>)ScienceApp::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", ScienceApp::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<ScienceApp, Long>)ScienceApp::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", ScienceApp::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<ScienceApp, String>)ScienceApp::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", ScienceApp::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<ScienceApp, Date>)ScienceApp::setStatusDate);
		attributeGetterFunctions.put(
			"lastPublishDate", ScienceApp::getLastPublishDate);
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			(BiConsumer<ScienceApp, Date>)ScienceApp::setLastPublishDate);
		attributeGetterFunctions.put("appName", ScienceApp::getAppName);
		attributeSetterBiConsumers.put(
			"appName", (BiConsumer<ScienceApp, String>)ScienceApp::setAppName);
		attributeGetterFunctions.put("appVersion", ScienceApp::getAppVersion);
		attributeSetterBiConsumers.put(
			"appVersion",
			(BiConsumer<ScienceApp, String>)ScienceApp::setAppVersion);
		attributeGetterFunctions.put("appType", ScienceApp::getAppType);
		attributeSetterBiConsumers.put(
			"appType", (BiConsumer<ScienceApp, String>)ScienceApp::setAppType);
		attributeGetterFunctions.put("exeFileName", ScienceApp::getExeFileName);
		attributeSetterBiConsumers.put(
			"exeFileName",
			(BiConsumer<ScienceApp, String>)ScienceApp::setExeFileName);
		attributeGetterFunctions.put("displayName", ScienceApp::getDisplayName);
		attributeSetterBiConsumers.put(
			"displayName",
			(BiConsumer<ScienceApp, String>)ScienceApp::setDisplayName);
		attributeGetterFunctions.put("description", ScienceApp::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<ScienceApp, String>)ScienceApp::setDescription);
		attributeGetterFunctions.put("startScript", ScienceApp::getStartScript);
		attributeSetterBiConsumers.put(
			"startScript",
			(BiConsumer<ScienceApp, String>)ScienceApp::setStartScript);
		attributeGetterFunctions.put(
			"finishScript", ScienceApp::getFinishScript);
		attributeSetterBiConsumers.put(
			"finishScript",
			(BiConsumer<ScienceApp, String>)ScienceApp::setFinishScript);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getScienceAppId() {
		return _scienceAppId;
	}

	@Override
	public void setScienceAppId(long scienceAppId) {
		_scienceAppId = scienceAppId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		_lastPublishDate = lastPublishDate;
	}

	@JSON
	@Override
	public String getAppName() {
		if (_appName == null) {
			return "";
		}
		else {
			return _appName;
		}
	}

	@Override
	public void setAppName(String appName) {
		_columnBitmask = -1L;

		if (_originalAppName == null) {
			_originalAppName = _appName;
		}

		_appName = appName;
	}

	public String getOriginalAppName() {
		return GetterUtil.getString(_originalAppName);
	}

	@JSON
	@Override
	public String getAppVersion() {
		if (_appVersion == null) {
			return "";
		}
		else {
			return _appVersion;
		}
	}

	@Override
	public void setAppVersion(String appVersion) {
		_columnBitmask |= APPVERSION_COLUMN_BITMASK;

		if (_originalAppVersion == null) {
			_originalAppVersion = _appVersion;
		}

		_appVersion = appVersion;
	}

	public String getOriginalAppVersion() {
		return GetterUtil.getString(_originalAppVersion);
	}

	@JSON
	@Override
	public String getAppType() {
		if (_appType == null) {
			return "";
		}
		else {
			return _appType;
		}
	}

	@Override
	public void setAppType(String appType) {
		_columnBitmask |= APPTYPE_COLUMN_BITMASK;

		if (_originalAppType == null) {
			_originalAppType = _appType;
		}

		_appType = appType;
	}

	public String getOriginalAppType() {
		return GetterUtil.getString(_originalAppType);
	}

	@JSON
	@Override
	public String getExeFileName() {
		if (_exeFileName == null) {
			return "";
		}
		else {
			return _exeFileName;
		}
	}

	@Override
	public void setExeFileName(String exeFileName) {
		_exeFileName = exeFileName;
	}

	@JSON
	@Override
	public String getDisplayName() {
		if (_displayName == null) {
			return "";
		}
		else {
			return _displayName;
		}
	}

	@Override
	public String getDisplayName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDisplayName(languageId);
	}

	@Override
	public String getDisplayName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDisplayName(languageId, useDefault);
	}

	@Override
	public String getDisplayName(String languageId) {
		return LocalizationUtil.getLocalization(getDisplayName(), languageId);
	}

	@Override
	public String getDisplayName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDisplayName(), languageId, useDefault);
	}

	@Override
	public String getDisplayNameCurrentLanguageId() {
		return _displayNameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDisplayNameCurrentValue() {
		Locale locale = getLocale(_displayNameCurrentLanguageId);

		return getDisplayName(locale);
	}

	@Override
	public Map<Locale, String> getDisplayNameMap() {
		return LocalizationUtil.getLocalizationMap(getDisplayName());
	}

	@Override
	public void setDisplayName(String displayName) {
		_displayName = displayName;
	}

	@Override
	public void setDisplayName(String displayName, Locale locale) {
		setDisplayName(displayName, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDisplayName(
		String displayName, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(displayName)) {
			setDisplayName(
				LocalizationUtil.updateLocalization(
					getDisplayName(), "DisplayName", displayName, languageId,
					defaultLanguageId));
		}
		else {
			setDisplayName(
				LocalizationUtil.removeLocalization(
					getDisplayName(), "DisplayName", languageId));
		}
	}

	@Override
	public void setDisplayNameCurrentLanguageId(String languageId) {
		_displayNameCurrentLanguageId = languageId;
	}

	@Override
	public void setDisplayNameMap(Map<Locale, String> displayNameMap) {
		setDisplayNameMap(displayNameMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDisplayNameMap(
		Map<Locale, String> displayNameMap, Locale defaultLocale) {

		if (displayNameMap == null) {
			return;
		}

		setDisplayName(
			LocalizationUtil.updateLocalization(
				displayNameMap, getDisplayName(), "DisplayName",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDescription(), languageId, useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescription(
		String description, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(
				LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(
				LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale) {

		if (descriptionMap == null) {
			return;
		}

		setDescription(
			LocalizationUtil.updateLocalization(
				descriptionMap, getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getStartScript() {
		if (_startScript == null) {
			return "";
		}
		else {
			return _startScript;
		}
	}

	@Override
	public void setStartScript(String startScript) {
		_startScript = startScript;
	}

	@JSON
	@Override
	public String getFinishScript() {
		if (_finishScript == null) {
			return "";
		}
		else {
			return _finishScript;
		}
	}

	@Override
	public void setFinishScript(String finishScript) {
		_finishScript = finishScript;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ScienceApp.class.getName()));
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ScienceApp.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> displayNameMap = getDisplayNameMap();

		for (Map.Entry<Locale, String> entry : displayNameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getDisplayName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			ScienceApp.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String displayName = getDisplayName(defaultLocale);

		if (Validator.isNull(displayName)) {
			setDisplayName(
				getDisplayName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDisplayName(
				getDisplayName(defaultLocale), defaultLocale, defaultLocale);
		}

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(
				getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(
				getDescription(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public ScienceApp toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ScienceApp>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ScienceAppImpl scienceAppImpl = new ScienceAppImpl();

		scienceAppImpl.setUuid(getUuid());
		scienceAppImpl.setScienceAppId(getScienceAppId());
		scienceAppImpl.setGroupId(getGroupId());
		scienceAppImpl.setCompanyId(getCompanyId());
		scienceAppImpl.setUserId(getUserId());
		scienceAppImpl.setUserName(getUserName());
		scienceAppImpl.setCreateDate(getCreateDate());
		scienceAppImpl.setModifiedDate(getModifiedDate());
		scienceAppImpl.setStatus(getStatus());
		scienceAppImpl.setStatusByUserId(getStatusByUserId());
		scienceAppImpl.setStatusByUserName(getStatusByUserName());
		scienceAppImpl.setStatusDate(getStatusDate());
		scienceAppImpl.setLastPublishDate(getLastPublishDate());
		scienceAppImpl.setAppName(getAppName());
		scienceAppImpl.setAppVersion(getAppVersion());
		scienceAppImpl.setAppType(getAppType());
		scienceAppImpl.setExeFileName(getExeFileName());
		scienceAppImpl.setDisplayName(getDisplayName());
		scienceAppImpl.setDescription(getDescription());
		scienceAppImpl.setStartScript(getStartScript());
		scienceAppImpl.setFinishScript(getFinishScript());

		scienceAppImpl.resetOriginalValues();

		return scienceAppImpl;
	}

	@Override
	public int compareTo(ScienceApp scienceApp) {
		int value = 0;

		value = getAppName().compareTo(scienceApp.getAppName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ScienceApp)) {
			return false;
		}

		ScienceApp scienceApp = (ScienceApp)object;

		long primaryKey = scienceApp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalUserId = _userId;

		_setOriginalUserId = false;

		_setModifiedDate = false;
		_originalStatus = _status;

		_setOriginalStatus = false;

		_originalAppName = _appName;

		_originalAppVersion = _appVersion;

		_originalAppType = _appType;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ScienceApp> toCacheModel() {
		ScienceAppCacheModel scienceAppCacheModel = new ScienceAppCacheModel();

		scienceAppCacheModel.uuid = getUuid();

		String uuid = scienceAppCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			scienceAppCacheModel.uuid = null;
		}

		scienceAppCacheModel.scienceAppId = getScienceAppId();

		scienceAppCacheModel.groupId = getGroupId();

		scienceAppCacheModel.companyId = getCompanyId();

		scienceAppCacheModel.userId = getUserId();

		scienceAppCacheModel.userName = getUserName();

		String userName = scienceAppCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			scienceAppCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			scienceAppCacheModel.createDate = createDate.getTime();
		}
		else {
			scienceAppCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			scienceAppCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			scienceAppCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		scienceAppCacheModel.status = getStatus();

		scienceAppCacheModel.statusByUserId = getStatusByUserId();

		scienceAppCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = scienceAppCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			scienceAppCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			scienceAppCacheModel.statusDate = statusDate.getTime();
		}
		else {
			scienceAppCacheModel.statusDate = Long.MIN_VALUE;
		}

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			scienceAppCacheModel.lastPublishDate = lastPublishDate.getTime();
		}
		else {
			scienceAppCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		scienceAppCacheModel.appName = getAppName();

		String appName = scienceAppCacheModel.appName;

		if ((appName != null) && (appName.length() == 0)) {
			scienceAppCacheModel.appName = null;
		}

		scienceAppCacheModel.appVersion = getAppVersion();

		String appVersion = scienceAppCacheModel.appVersion;

		if ((appVersion != null) && (appVersion.length() == 0)) {
			scienceAppCacheModel.appVersion = null;
		}

		scienceAppCacheModel.appType = getAppType();

		String appType = scienceAppCacheModel.appType;

		if ((appType != null) && (appType.length() == 0)) {
			scienceAppCacheModel.appType = null;
		}

		scienceAppCacheModel.exeFileName = getExeFileName();

		String exeFileName = scienceAppCacheModel.exeFileName;

		if ((exeFileName != null) && (exeFileName.length() == 0)) {
			scienceAppCacheModel.exeFileName = null;
		}

		scienceAppCacheModel.displayName = getDisplayName();

		String displayName = scienceAppCacheModel.displayName;

		if ((displayName != null) && (displayName.length() == 0)) {
			scienceAppCacheModel.displayName = null;
		}

		scienceAppCacheModel.description = getDescription();

		String description = scienceAppCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			scienceAppCacheModel.description = null;
		}

		scienceAppCacheModel.startScript = getStartScript();

		String startScript = scienceAppCacheModel.startScript;

		if ((startScript != null) && (startScript.length() == 0)) {
			scienceAppCacheModel.startScript = null;
		}

		scienceAppCacheModel.finishScript = getFinishScript();

		String finishScript = scienceAppCacheModel.finishScript;

		if ((finishScript != null) && (finishScript.length() == 0)) {
			scienceAppCacheModel.finishScript = null;
		}

		return scienceAppCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ScienceApp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ScienceApp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ScienceApp, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ScienceApp)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ScienceApp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ScienceApp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ScienceApp, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ScienceApp)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ScienceApp>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ScienceApp.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _scienceAppId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private Date _lastPublishDate;
	private String _appName;
	private String _originalAppName;
	private String _appVersion;
	private String _originalAppVersion;
	private String _appType;
	private String _originalAppType;
	private String _exeFileName;
	private String _displayName;
	private String _displayNameCurrentLanguageId;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private String _startScript;
	private String _finishScript;
	private long _columnBitmask;
	private ScienceApp _escapedModel;

}