/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.sx.spyglass.model.impl;

import com.sx.spyglass.model.ScienceApp;
import com.sx.spyglass.service.ScienceAppLocalServiceUtil;

/**
 * The extended model base implementation for the ScienceApp service. Represents a row in the &quot;SXSpyglass_ScienceApp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ScienceAppImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ScienceAppImpl
 * @see ScienceApp
 * @generated
 */
public abstract class ScienceAppBaseImpl
	extends ScienceAppModelImpl implements ScienceApp {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a science app model instance should use the <code>ScienceApp</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ScienceAppLocalServiceUtil.addScienceApp(this);
		}
		else {
			ScienceAppLocalServiceUtil.updateScienceApp(this);
		}
	}

}